module.exports = {
  productos: [
    {
      _id: "1",
      nombre: "Pan de integral con trozos de calabaza",
      categoria: ["Integral"],
      imagen: "src/assets/img/panintegralcalabaza.jpg",
      precio: 120,
      rating: 4.5,
      stock: 36,
      vistos: 102,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "2",
      nombre: "Pan de integral con miel",
      categoria: ["Integral", "Dulce"],
      imagen: "src/assets/img/pan-de-harina-integral-miel.jpg",
      precio: 100,
      rating: 4.0,
      stock: 15,
      vistos: 132,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "3",
      nombre: "Pan de avena con miel",
      categoria: ["Avena", "Dulce"],
      imagen: "src/assets/img/panavenamiel.jpg",
      precio: 130,
      rating: 5,
      stock: 42,
      vistos: 12,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "4",
      nombre: "Pan de avena con trozos de zapallo",
      categoria: ["Avena"],
      imagen: "src/assets/img/panavenazapallo.jpg",
      precio: 130,
      rating: 5,
      stock: 92,
      vistos: 48,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "5",
      nombre: "Marraqueta",
      categoria: ["Clásico"],
      imagen: "src/assets/img/marraqueta.jpg",
      precio: 70,
      rating: 3.5,
      stock: 103,
      vistos: 12,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "6",
      nombre: "Pan de frica",
      categoria: ["Clásico"],
      imagen: "src/assets/img/panfrica.jpg",
      precio: 50,
      rating: 3.5,
      stock: 105,
      vistos: 67,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "7",
      nombre: "Pan de molde",
      categoria: ["Clásico"],
      imagen: "src/assets/img/panmolde.jpg",
      precio: 40,
      rating: 4,
      stock: 201,
      vistos: 23,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "8",
      nombre: "Pan dulce de hamburguesa",
      categoria: ["Dulce", "Clásico"],
      imagen: "src/assets/img/pandulcehamburguesa.jpg",
      precio: 80,
      rating: 4.5,
      stock: 6,
      vistos: 61,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "9",
      nombre: "Pan de huevo",
      categoria: ["Dulce", "Clásico"],
      imagen: "src/assets/img/panhuevo.jpg",
      precio: 100,
      rating: 4.5,
      stock: 71,
      vistos: 94,
      descripcion: "Pan del gueno bla bla bla",
    },
  ],
};
