module.exports = {
  productos: [
    {
      _id: "1",
      nombre: "Pan de integral con trozos de calabaza",
      categoria: "Pan integral",
      imagen: "src/assets/img/panintegralcalabaza.jpg",
      precio: 120,
      rating: 4.5,
      vistos: 10,
      stock: 36,
      vistos: 102,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "2",
      nombre: "Pan de integral con miel",
      categoria: "Pan integral",
      imagen: "src/assets/img/pan-de-harina-integral-miel.jpg",
      precio: 100,
      rating: 4.0,
      vistos: 17,
      stock: 15,
      vistos: 132,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "3",
      nombre: "Pan de avena con miel",
      categoria: "Pan de avena",
      imagen: "src/assets/img/panavenamiel.jpg",
      precio: 130,
      rating: 5,
      vistos: 31,
      stock: 42,
      vistos: 12,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "4",
      nombre: "Pan de avena con trozos de zapallo",
      categoria: "Pan de avena",
      imagen: "src/assets/img/panavenazapallo.jpg",
      precio: 130,
      rating: 5,
      vistos: 54,
      stock: 92,
      vistos: 48,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "5",
      nombre: "Marraqueta",
      categoria: "Pan clásico",
      imagen: "src/assets/img/marraqueta.jpg",
      precio: 70,
      rating: 3.5,
      vistos: 40,
      stock: 103,
      vistos: 12,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "6",
      nombre: "Pan de frica",
      categoria: "Pan clásico",
      imagen: "src/assets/img/panfrica.jpg",
      precio: 50,
      rating: 3.5,
      vistos: 43,
      stock: 105,
      vistos: 67,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "7",
      nombre: "Pan de molde",
      categoria: "Pan clásico",
      imagen: "src/assets/img/panmolde.jpg",
      precio: 40,
      rating: 4,
      vistos: 102,
      stock: 201,
      vistos: 23,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "8",
      nombre: "Pan dulce de hamburguesa",
      categoria: "Pan dulce",
      imagen: "src/assets/img/pandulcehamburguesa.jpg",
      precio: 80,
      rating: 4.5,
      vistos: 10,
      stock: 6,
      vistos: 61,
      descripcion: "Pan del gueno bla bla bla",
    },
    {
      _id: "9",
      nombre: "Pan de huevo",
      categoria: "Pan dulce",
      imagen: "src/assets/img/panhuevo.jpg",
      precio: 100,
      rating: 4.5,
      vistos: 16,
      stock: 71,
      vistos: 94,
      descripcion: "Pan del gueno bla bla bla",
    },
  ],
};
